[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_ENV = "production"

[functions]
  external_node_modules = ["express", "sqlite3", "bcrypt"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA fallback - serve index.html for all routes that don't match static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
